In [4]:
array3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array3)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
import numpy as np
array3 = np.array([1])
print(array3)



[1]


In [5]:
array3*array3

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [6]:
array3**array3

array([[        1,         4,        27],
       [      256,      3125,     46656],
       [   823543,  16777216, 387420489]])

In [13]:
array1 = np.array([1, 2, 3, 4, 5, 6])

In [14]:
array1

array([1, 2, 3, 4, 5, 6])

In [16]:
arr = array1[2:5]
print(arr)

[3 4 5]


In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [1]:
import numpy as np

arr = np.array([1, 2, 4, 6])

reverse_arr = arr[::-1]
print(reverse_arr)

[6 4 2 1]
