In [18]:
import numpy as np

In [19]:
array1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [20]:
array1.shape

(2, 5)

In [21]:
array1.dtype

dtype('int32')

In [22]:
array2 = np.array([[1.8, 2.3, 3.0, 4, 5],[6.9, 7.3, 8.1, 9, 10]], dtype = 'int32' )
print(array2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [23]:
np.zeros(4)

array([0., 0., 0., 0.])

In [24]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [25]:
np.ones(4)

array([1., 1., 1., 1.])

In [26]:
np.ones(4).dtype

dtype('float64')

In [27]:
np.empty((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [28]:
array1*array1

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

In [29]:
array1/array1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
array1**array1

array([[         1,          4,         27,        256,       3125],
       [     46656,     823543,   16777216,  387420489, 1410065408]])

# Slicing

In [ ]:
array3 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(array3)

In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
new_arr =arr[:,0]
print(new_arr)

[1 5]


In [3]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
new_arr =arr[:,[0]]
print(new_arr)

[[1]
 [5]]
