In [1]:
import numpy as np

In [7]:
arr = np.arange(10000)

In [8]:
pythlist = list(range(10000))

In [10]:
%time for _ in range(10): [item*3 for item in pythlist]

CPU times: total: 0 ns
Wall time: 25.7 ms


In [11]:
%time for _ in range(10): arr = arr*3

CPU times: total: 0 ns
Wall time: 14.7 ms


In [12]:
np.array([3,4,5,6,7])

array([3, 4, 5, 6, 7])

In [3]:
#1D Array
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [4]:
#2D Array
X = ([[1.8, 2.5, 3.14],
      [4, 5, 6]])
arr2 = np.array(X)
arr2

array([[1.8 , 2.5 , 3.14],
       [4.  , 5.  , 6.  ]])

In [5]:
#3D Array
Y = ([[1,2,3],
      [4,5,6],
      [7,8,9]])
arr3 = np.array(Y)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
print('data type arr1 ', arr1.dtype) 
print('data type arr2 ', arr2.dtype)
print('data type arr3 ', arr3.dtype)

data type arr1  int32
data type arr2  float64
data type arr3  int32


In [7]:
import numpy as np
arr = np.array([0, 5, 4, 0, 4, 4, 3, 0, 0, 5, 2, 1, 1, 9])
print(np.bincount(arr))

[4 2 1 1 3 2 0 0 0 1]
